// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using BlazorSimpleSurvey.Models;

namespace BlazorSimpleSurvey.Data
{
    public partial class SimpleSurveyContext : DbContext
    {
        public SimpleSurveyContext()
        {
        }

        public SimpleSurveyContext(DbContextOptions<SimpleSurveyContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Users> Users { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Users>(entity =>
            {
                entity.Property(e => e.AuthenticationType)
                    .IsRequired()
                    .HasMaxLength(50);

                entity.Property(e => e.CreatedDate).HasColumnType("datetime");

                entity.Property(e => e.DisplayName).HasMaxLength(1000);

                entity.Property(e => e.Email).HasMaxLength(1000);

                entity.Property(e => e.FirstName).HasMaxLength(500);

                entity.Property(e => e.IdentityProvider)
                    .IsRequired()
                    .HasMaxLength(500);

                entity.Property(e => e.LastAuthTime).HasColumnName("LastAuth_time");

                entity.Property(e => e.LastIpaddress)
                    .IsRequired()
                    .HasColumnName("LastIPAddress")
                    .HasMaxLength(50);

                entity.Property(e => e.LastName).HasMaxLength(500);

                entity.Property(e => e.LastidpAccessToken)
                    .HasColumnName("Lastidp_access_token")
                    .HasMaxLength(4000);

                entity.Property(e => e.Objectidentifier)
                    .IsRequired()
                    .HasMaxLength(500);

                entity.Property(e => e.SignupMethod).HasMaxLength(500);

                entity.Property(e => e.UpdatedDate).HasColumnType("datetime");

                entity.Property(e => e.UserName)
                    .IsRequired()
                    .HasMaxLength(1000);
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}