// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace BlazorSimpleSurvey.Models
{
    public partial class Logs
    {
        public int LogId { get; set; }
        public DateTime LogDate { get; set; }
        public string LogType { get; set; }
        public string LogDetail { get; set; }
        public int? LogUserId { get; set; }
        public string LogIpaddress { get; set; }

        public virtual Users LogUser { get; set; }
    }
}