// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace BlazorSimpleSurvey.Models
{
    public partial class SurveyItem
    {
        public SurveyItem()
        {
            SurveyAnswer = new HashSet<SurveyAnswer>();
        }

        public int Id { get; set; }
        public int Survey { get; set; }
        public string ItemLabel { get; set; }
        public string ItemType { get; set; }
        public string ItemValue { get; set; }
        public DateTime? ItemDateValue { get; set; }
        public string Required { get; set; }
        public int? SurveyChoiceId { get; set; }

        public virtual SurveyItemOption SurveyChoice { get; set; }
        public virtual Survey SurveyNavigation { get; set; }
        public virtual ICollection<SurveyAnswer> SurveyAnswer { get; set; }
    }
}