// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace BlazorSimpleSurvey.Models
{
    public partial class SurveyAnswer
    {
        public int Id { get; set; }
        public int SurveyItemId { get; set; }
        public string AnswerValue { get; set; }
        public DateTime? AnswerValueDateTime { get; set; }
        public int UserId { get; set; }

        public virtual SurveyItem SurveyItem { get; set; }
        public virtual Users User { get; set; }
    }
}