// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace BlazorSimpleSurvey.Models
{
    public partial class SurveyItemOption
    {
        public int Id { get; set; }
        public int SurveyItem { get; set; }
        public string OptionLabel { get; set; }

        public virtual SurveyItem SurveyItemNavigation { get; set; }
    }
}