// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace BlazorSimpleSurvey.Models
{
    public partial class SurveyItemOption
    {
        public SurveyItemOption()
        {
            SurveyItem = new HashSet<SurveyItem>();
        }

        public int Id { get; set; }
        public string OptionLabel { get; set; }

        public virtual ICollection<SurveyItem> SurveyItem { get; set; }
    }
}